name: prod-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ninek-9 --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ghcr.io/ninek-9/accessable-maps-places:prod --push .

  deploy-to-aci:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: accessable-maps
          dns-name-label: accessable-maps
          image: ghcr.io/ninek-9/accessable-maps-places:prod
          registry-login-server: ghcr.io
          registry-username: ninek-9
          registry-password: ${{ secrets.GHCR_TOKEN }}
          secure-environment-variables: GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          name: accessable-maps
          location: 'east us'
